#!/usr/bin/env python3

from __future__ import annotations

from log_analysis.battery_model import (
    align_numeric_series,
    build_estimated_current_series,
    build_phase_summary,
    build_trace_points,
    build_subsystem_breakdown_series,
    count_true_transitions,
    count_true_transitions_for_filter,
    estimate_internal_resistance,
    estimate_resting_voltage,
    integrate_below_threshold,
    percentile,
    summarize_component_currents_for_filter,
    summarize_current_series,
    summarize_enabled_component_currents,
)
from log_analysis.cli import (
    BatterySummary,
    analyze_log,
    analyze_log_safe,
    analyze_logs,
    build_error_summary,
    detect_output_format,
    emit_output,
    format_optional_float,
    main,
    parse_args,
    render_text,
)
from log_analysis.config import DEFAULT_CONFIG, apply_cli_overrides, deep_merge, load_config
from log_analysis.scoring import determine_dominant_cause, rate_battery, rate_battery_condition, rate_load_assessment
from log_analysis.wpilog import (
    EntryInfo,
    LogRecord,
    decode_control_start,
    decode_value,
    expand_paths,
    iter_records,
    load_series,
    split_series,
    state_at,
    value_at,
)

__all__ = [
    "BatterySummary",
    "DEFAULT_CONFIG",
    "EntryInfo",
    "LogRecord",
    "align_numeric_series",
    "analyze_log",
    "analyze_log_safe",
    "analyze_logs",
    "apply_cli_overrides",
    "build_error_summary",
    "build_estimated_current_series",
    "build_phase_summary",
    "build_subsystem_breakdown_series",
    "build_trace_points",
    "count_true_transitions",
    "count_true_transitions_for_filter",
    "decode_control_start",
    "decode_value",
    "deep_merge",
    "detect_output_format",
    "determine_dominant_cause",
    "emit_output",
    "estimate_internal_resistance",
    "estimate_resting_voltage",
    "expand_paths",
    "format_optional_float",
    "integrate_below_threshold",
    "iter_records",
    "load_config",
    "load_series",
    "main",
    "parse_args",
    "percentile",
    "rate_battery",
    "rate_battery_condition",
    "rate_load_assessment",
    "render_text",
    "split_series",
    "state_at",
    "summarize_component_currents_for_filter",
    "summarize_current_series",
    "summarize_enabled_component_currents",
    "value_at",
]

if __name__ == "__main__":
    main()
